# Generated by Django 3.2 on 2021-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'CsvUpload',
                'verbose_name_plural': 'CsvUploads',
                'db_table': 'csv_upload',
            },
        ),
    ]
